name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      env :
        CI: "Github Actions"
      run : go test -v --race ./...

    - name: Build
      run: go run ./scripts/deploy/build_binaries.go

    - name: Benchmark
      run: go test -v ./... -bench=./...  2>&1 | tee $GITHUB_WORKSPACE/latest-benchmarks.txt

    - name: Upload bencmark artifacts
      uses: actions/upload-artifact@master
      with:
        name: benchmark-report.txt
        path: latest-benchmarks.txt
   
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release
